<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>OpenVisionLab.PropertyGrid</RootNamespace>
    <AssemblyName>PropertyGrid.Abstractions</AssemblyName>
    <Deterministic>true</Deterministic>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
</Project>
