<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RootNamespace>OpenVisionLab.ImageCanvas</RootNamespace>
    <AssemblyName>OpenVisionLab.ImageCanvas</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="OpenCvSharp">
      <HintPath>$(OpenVisionLabVisionSdkDllRoot)OpenCvSharp.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="SharpGL">
      <HintPath>$(OpenVisionLabDllRoot)SharpGL\SharpGL.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="SharpGL.WinForms">
      <HintPath>$(OpenVisionLabDllRoot)SharpGL\SharpGL.WinForms.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ViewModel\AutoAlignTeachingViewModel.cs" />
    <Compile Remove="ViewModel\AutoWarpageTeachingViewModel.cs" />
    <Compile Remove="ViewModel\LayoutItemViewModel.cs" />
    <Compile Remove="View\AddRoiArrayView.xaml.cs" />
    <Compile Remove="View\AutoAlignTeachingView.xaml.cs" />
    <Compile Remove="View\AutoWarpageTeachingView.xaml.cs" />
    <Compile Remove="Converter\BooleanToEyeIconConverter .cs" />
    <Page Remove="View\AddRoiArrayView.xaml" />
    <Page Remove="View\AutoAlignTeachingView.xaml" />
    <Page Remove="View\AutoWarpageTeachingView.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenVisionLab.Localization\OpenVisionLab.Localization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(OpenVisionLabOpenCvSharpDllRoot)OpenCvSharpExtern.dll">
      <Link>OpenCvSharpExtern.dll</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
