<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <UseSystemDrawing>true</UseSystemDrawing>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenVisionLab\OpenVisionLab.csproj" />
    <Reference Include="OpenVisionLab.Core">
      <HintPath>$(OpenVisionLabVisionSdkDllRoot)OpenVisionLab.Core.dll</HintPath>
    </Reference>
    <Reference Include="OpenVisionLab.Vision2D">
      <HintPath>$(OpenVisionLabVisionSdkDllRoot)OpenVisionLab.Vision2D.dll</HintPath>
    </Reference>
    <Reference Include="OpenVisionLab.Vision2D.Blob">
      <HintPath>$(OpenVisionLabVisionSdkDllRoot)OpenVisionLab.Vision2D.Blob.dll</HintPath>
    </Reference>
    <Reference Include="OpenCvSharp">
      <HintPath>$(OpenVisionLabVisionSdkDllRoot)OpenCvSharp.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
